name: job_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  bottom_bar_matu: ^1.3.1
  buttons_tabbar: ^1.3.8
  chatview: ^1.3.1
  cloud_firestore: ^4.15.4
  country_code_picker: ^3.0.0
  country_picker: ^2.0.24
  country_pickers: ^2.0.0
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  file_picker: ^6.1.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_countdown_timer: ^4.1.0
  flutter_expand_view: ^1.6.2
  flutter_glow: ^0.3.0
  flutter_holo_date_picker: ^1.1.3
  flutter_pdfview: ^1.3.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  intl_phone_field: ^3.2.0
  lottie: ^3.0.0
  motion_tab_bar: ^2.0.4
  open_app_file: ^4.0.2
  pinput: ^4.0.0
  recase: ^4.1.0
  smooth_page_indicator: ^1.1.0
  svg_flutter: ^0.0.1
  syncfusion_flutter_pdfviewer: ^24.2.7
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
